version: "3.9"

services:

  speedy-1:
    hostname: speedy-1
    container_name: speedy-1
    image: gcr.io/distroless/static-debian11
    command: [ "./main" ]
    volumes:
      - ./bin/main:/main
    ports:
      - "8081:8080"

  speedy-2:
    hostname: speedy-2
    container_name: speedy-2
    image: gcr.io/distroless/static-debian11
    command: [ "./main" ]
    volumes:
      - ./bin/main:/main
    ports:
      - "8082:8080"

  speedy-3:
    hostname: speedy-3
    container_name: speedy-3
    image: gcr.io/distroless/static-debian11
    command: [ "./main" ]
    volumes:
      - ./bin/main:/main
    ports:
      - "8083:8080"
