name: premerge

on:
  push:
    branches:
      - master
  pull_request:

env:
  GO_VERSION: '1.21'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Running tests
        run: make test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Running linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --issues-exit-code 1 --print-issued-lines=true --config .golangci.yml ./...
